### ISSUE TITLE
Forward Overlap may not be calculated correctly

### ISSUE THREAD

**Issue by hkmanching** [UCANR-IGIS/uasimg#9]
I am getting values that are mainly zero when calculating overlap for images in a flight. When I look at the output, the images are not in an order that makes sense (DJI_003, DJI_0020, DJI_0018). I would expect the order to be based on create time so that the overlap is calculated on images in the sequence it was created.

**Comment by hkmanching** [comment]
Going through the code, I think sorting exif_df after the create datetimeoriginal (line 417 of uas_info.r) will correct this. I tried on raw code and worked fine.

**Comment by ajlyons** [comment]
Thanks for pointing this out, and identifying a fix. It would be uncommon for images sorted alphabetically (which is how exiftool reads them) to not also be sequential in time, but sorting them using the datetimeoriginal field in the EXIF data is easy and eliminates this possibility. This has been fixed in version 1.9.0.
